name: rg_backend_operations_app
description: Standalone backend operations dashboard for RG Travel Solution
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^7.0.2
  geocoding: ^3.0.0
  http: ^1.2.2
  latlong2: ^0.9.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
